gestion_contact/urls.py
from django.contrib import admin
from django.urls import path
from contact import views  


urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact', views.contact),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy), 
]

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):  
    cid = models.CharField(max_length=20)  
    cname = models.CharField(max_length=100)
    clastname = models.CharField(max_length=100) 
    cemail = models.EmailField()  
    cphone = models.CharField(max_length=8)
    

    class Meta:  
        db_table = "contact"

contact/forms.py
from django import forms  

from contact.models import Contact  
class ContactForm(forms.ModelForm):  
    class Meta:  
        model = Contact  
        fields = "__all__"  

contact/views.py
from django.shortcuts import render

# Create your views here.
from contact.forms import ContactForm  
from contact.models import Contact  
# Create your views here.  
def contact(request):  
    if request.method == "POST":  
        form = ContactForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ContactForm()  
    return render(request,'index.html',{'form':form})  

def show(request):  
    contact = Contact.objects.all()  
    return render(request,"show.html",{'contact':contact})
  
def edit(request, id):  
    contact = Contact.objects.get(id=id)  
    return render(request,'edit.html', {'contact':contact})  

def update(request, id):  
    contact = Contact.objects.get(id=id)  
    form = ContactForm(request.POST, instance = contact)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'contact': contact})  

def destroy(request, id):  
    contact = Contact.objects.get(id=id)  
    contact.delete()  
    return redirect("/show")  

contact/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}
 
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{contact.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Id:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ contact.cid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_cname" required maxlength="100" value="{{ contact.cname }}" />  
    </div>  
  </div>  
</div>  
<div class="form-group row">  
  <label class="col-sm-2 col-form-label">Contact Name:</label>  
  <div class="col-sm-4">  
      <input type="text" name="ename" id="id_clastname" required maxlength="100" value="{{ contact.clastname }}" />  
  </div>  
</div>  
<div class="form-group row">  
  <label class="col-sm-2 col-form-label">Contact Email:</label>  
  <div class="col-sm-4">  
      <input type="email" name="eemail" id="id_cphone" required maxlength="254" value="{{ contact.cphone }}" />  
  </div>  
</div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Email:</label>  
    <div class="col-sm-4">  
        <input type="email" name="eemail" id="id_cemail" required maxlength="254" value="{{ contact.cemail }}" />  
    </div>  
  </div>  
    
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

contact/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">contact Id:</label>  
    <div class="col-sm-4">  
      {{ form.cid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Name:</label>  
    <div class="col-sm-4">  
      {{ form.cname }}  
    </div>  
    <div class="form-group row">  
      <label class="col-sm-2 col-form-label">Contact Last Name:</label>  
      <div class="col-sm-4">  
        {{ form.clastname }}  
      </div>
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Email:</label>  
    <div class="col-sm-4">  
      {{ form.cemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact Contact:</label>  
    <div class="col-sm-4">  
      {{ form.cphone }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

contact/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Contact Records</title>  
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Contact ID</th>  
        <th>Contact Name</th>  
        <th>Contact Last Name</th>  
        <th>Contact Email</th>  
        <th>Contact phone</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for contact in contacts %}  
    <tr>  
        <td>{{ contact.cid }}</td>  
        <td>{{ contact.cname }}</td>  
        <td>{{ contact.clastname }}</td>  
        <td>{{ contact.cphone }}</td>  
        <td>{{ contact.cemail }}</td>  
        <td>  
            <a href="/edit/{{ contact.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ contact.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/contact" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  